[package]
name = "yapwir-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.7", features = ["csr"] }
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
console_error_panic_hook = "0.1.7"
gloo-timers = { version = "0.3.0", features = ["futures"] }

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.50"
serde-wasm-bindgen = "0.6"

[workspace]
members = ["src-tauri"]
